name = "MixedModelsGadfly"
uuid = "058baad1-c367-4912-a4ff-3746f7f06d22"
authors = ["Phillip Alday <me@phillipalday.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
